# Generated by Django 5.0.6 on 2025-08-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('is_rentable', models.BooleanField(default=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('tracking_mode', models.CharField(choices=[('none', 'None'), ('serial', 'Serial Tracked')], default='none', max_length=10)),
                ('rental_units', models.CharField(choices=[('hour', 'Hour'), ('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], default='day', max_length=10)),
                ('min_duration', models.PositiveIntegerField(default=1)),
                ('max_duration', models.PositiveIntegerField(blank=True, null=True)),
                ('buffer_before_hours', models.PositiveIntegerField(default=0)),
                ('buffer_after_hours', models.PositiveIntegerField(default=0)),
                ('deposit_required', models.BooleanField(default=False)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('late_fee_type', models.CharField(choices=[('fixed', 'Fixed'), ('per_unit', 'Per Unit Time')], default='per_unit', max_length=10)),
                ('late_fee_unit', models.CharField(choices=[('hour', 'Hour'), ('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], default='day', max_length=10)),
                ('late_fee_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
