# Generated by Django 5.0.6 on 2025-08-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_days_customer', models.PositiveIntegerField(default=2)),
                ('lead_days_end_user', models.PositiveIntegerField(default=2)),
                ('email_template_customer', models.TextField(blank=True)),
                ('email_template_end_user', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
