# Generated by Django 5.0.6 on 2025-08-15 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=40, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('quoted', 'Quoted'), ('confirmed', 'Confirmed'), ('out', 'Out'), ('returned', 'Returned'), ('invoiced', 'Invoiced'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=12)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('expected_return_at', models.DateTimeField()),
                ('actual_return_at', models.DateTimeField(blank=True, null=True)),
                ('total_rent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('taxes_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fees_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payment_status', models.CharField(default='unpaid', max_length=20)),
                ('contract_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('pickup', 'Pickup'), ('return', 'Return')], max_length=10)),
                ('scheduled_at', models.DateTimeField()),
                ('items', models.JSONField(default=list)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('damage_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='rentals.rentalorder')),
            ],
        ),
        migrations.CreateModel(
            name='RentalOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit', models.CharField(default='day', max_length=10)),
                ('duration_qty', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rule_applied', models.CharField(blank=True, max_length=255)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='rentals.rentalorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('collected', 'Collected'), ('returned', 'Returned'), ('expired', 'Expired')], default='reserved', max_length=10)),
                ('allocated_serials', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='rentals.rentalorderline')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
            ],
            options={
                'indexes': [models.Index(fields=['product', 'start_at', 'end_at'], name='rentals_res_product_9027e4_idx')],
            },
        ),
    ]
