# Generated by Django 5.0.6 on 2025-08-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalorder',
            name='number',
            field=models.CharField(blank=True, max_length=40, unique=True),
        ),
    ]
