# Generated by Django 5.0.6 on 2025-08-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_alter_rentalorder_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalorder',
            name='expected_return_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
